#!/usr/bin/env bash
#
# Transforma tabular data packages a Excel

# Esperamos que la primer tabla ('resources[0]') sea la única tabla de datos (de lo contario no lo exportaríamos a excel)
nombre_tabla_datos=$(< datapackage.json jq '.resources[0].path' | cut --delimiter=\" --fields=2)
# Los metadatos de columna de la tabla 'resources[0]' se encuentran en: 'resources[0].schema.fields'
< datapackage.json jq '.resources[0].schema.fields' | in2csv --format json --verbose > metadatos_columna.csv
# A los metadatos de la tabla 'resources[0]' debemos quitarle ('del') los metadatos de las columnas '.schema'
< datapackage.json jq '[.resources[0] | del(.schema)]' | in2csv --format json --verbose > metadatos_tabla.csv
# A los metadatos del paquete debemos quitarle ('del') los metadatos de las tablas '.resources'
< datapackage.json jq '[del(.resources)]' | in2csv --format json --verbose > metadatos_paquete.csv
ssconvert --merge-to tabla.xlsx $nombre_tabla_datos metadatos_columna.csv metadatos_tabla.csv metadatos_paquete.csv
rm metadatos_columna.csv metadatos_tabla.csv metadatos_paquete.csv
