name: Tests
on:
  push:
    branches:
      - develop
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/testmake .
    - name: Ejecuta pruebas
      run: docker run islasgeci/testmake make init
