name: Daily test
on:
  push:
    branches:
      - develop
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@main
    - name: Instala geci-testmake
      run: make install
    - name: Dummy geci-testmake
      env:
        TABLERO_API_SECRET_KEY: ${{ secrets.TABLERO_API_SECRET_KEY }}
        BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
        BITBUCKET_PASSWORD: ${{ secrets.BITBUCKET_PASSWORD }}
      run: geci-testmake hola mundo
